### ISSUE TITLE
i found franz portable autorun after rebooting

### ISSUE THREAD

**Issue by beppe9000** [portapps/franz-portable#1]
i think this should be not happening
windows 10

**Comment by crazy-max** [comment]
Hi @beppe9000, yes we can disable this behaviour

**Comment by beppe9000** [comment]
yeah, if I had removed the usb drive it would have left an orphan autorun entry :)

**Comment by crazy-max** [comment]
@beppe9000 Should be solved with latest release : https://portapps.io/app/franz-portable/#download
