### ISSUE TITLE
Disable delay

### ISSUE THREAD

**Issue by fogoat** [portapps/franz-portable#2]
https://github.com/kytwb/ferdi

Hi, some of us are annoyed by the wait counter: https://github.com/meetfranz/franz/issues/1167

Someone made a repo that has this removed. I like your portapps, would you consider compiling from that code instead of the main repo?

**Comment by crazy-max** [comment]
Seeing [the changes](https://github.com/kytwb/ferdi/commit/82a4da1896188f0885ddb0c67f2ab3c4dd40a8ce) made to the fork I think we can simply add an option to disable the delay here.

**Comment by crazy-max** [comment]
@sunk818 Should be fixed in latest release. See [configuration section](https://portapps.io/app/franz-portable/#infos) for more info.
