### ISSUE TITLE
Empty folder %APPDATA%\Franz\logs left

### ISSUE THREAD

**Issue by Makazzz** [portapps/franz-portable#3]
### Behaviour
When finishing using franz-portable, there are two folder left in Roaming/Franz/log.
#### Steps to reproduce this issue

1. Open franz portable
2. Using it
3. Close the app

#### Expected behaviour

> These two are supposed to follow the data folder or be deleted automaticly

#### Actual behaviour

> These two folder stay in the computer (%appdata% or Roaming)

### Configuration

**App release / arch** : 5.2.0-4 win32

**Operating system** : Windows Pro 64 bits

**Winver screenshot** : https://image.noelshack.com/fichiers/2019/36/6/1567824895-winvers.png

### Screenshots

https://image.noelshack.com/fichiers/2019/36/6/1567825702-franz-leftover.png
https://image.noelshack.com/fichiers/2019/36/6/1567825702-franz-leftover1.png

### Logs
[franz-portable.log](https://github.com/portapps/franz-portable/files/3586180/franz-portable.log)

**Comment by crazy-max** [comment]
@Makazzz `%APPDATA%\Franz\logs` is hardcoded by Electron (as other apps based on Electron like Postman, Rambox, Skype). I will take a look if I can handle it.

**Comment by Makazzz** [comment]
> @Makazzz `%APPDATA%\Franz\logs` is hardcoded by Electron (as other apps based on Electron like Postman, Rambox, Skype). I will take a look if I can handle it.

Thank you.

**Comment by bzsimon** [comment]
no zoom function ... when will be this function implemented again? Portable last version under win10

**Comment by crazy-max** [comment]
@bzsimon I don't bring support to Franz directly. If you want support for Franz, open an issue on the official repository: https://github.com/meetfranz/franz.

**Comment by crazy-max** [comment]
@Makazzz  This has been fixed through an opt-in `cleanup` config parameter in the latest release. See Configuration section in https://portapps.io/app/franz-portable/#infos for more info.
