### ISSUE TITLE
App is not portable [5.6.1-11]

### ISSUE THREAD

**Issue by murat-mehmet** [portapps/franz-portable#40]
### Behaviour
I've just updated app to the latest and it keeps asking credentials. It seems like this is broken for some versions. I had to downgrade to 5.1.0-2 to make it work properly.

#### Steps to reproduce this issue

1. Install app on a portable drive.
2. Enter credentials and move to a different OS or machine. In my case I'm just using a UWF enabled machine.

#### Expected behaviour

It should remember credentials.

#### Actual behaviour

It does not remember credentials.

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 5.6.1-11 win64

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Edu 64 bits

**Winver screenshot** :

![Screenshot 2021-07-15 141710](https://user-images.githubusercontent.com/7101489/125779515-f5047608-07a0-490e-b63c-a4b755fca63c.png)

### Screenshots

none

### Logs

Join the log file `log\[appname]-portable.log` to this issue.

**Comment by murat-mehmet** [comment]
Ok I updated to the 5.4.1-9 and it works properly.
5.5.0-10 and the latest version is broken.

**Comment by crazy-max** [comment]
Will take a look, thanks for your feedback.

**Comment by crazy-max** [comment]
Can you try with the latest realease?
